
services:
 
  app:
    image: com-app
    build:
      context: ./ 
      target: dev
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
    environment:
      - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
      - NODE_ENV= "development"
      - HOSTNAME=${NEXT_PUBLIC_HOST}
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${NEXT_PUBLIC_HOST}`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.app-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nas.tls=true"  
      - "info.url=https://${NEXT_PUBLIC_HOST}"
    networks:
      - localhost_net





networks:
  localhost_net:
    external: true
